/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class philipyexushen_opencvhandler_HandlerWrapper */

#ifndef _Included_philipyexushen_opencvhandler_HandlerWrapper
#define _Included_philipyexushen_opencvhandler_HandlerWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     philipyexushen_opencvhandler_HandlerWrapper
 * Method:    houghCircles
 * Signature: ([IIIDDDDII)[I
 */
JNIEXPORT jintArray JNICALL Java_philipyexushen_opencvhandler_HandlerWrapper_houghCircles
  (JNIEnv *, jclass, jintArray, jint, jint, jdouble, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     philipyexushen_opencvhandler_HandlerWrapper
 * Method:    generalizedHoughBallard
 * Signature: ([I[IIIDDIII)[F
 */
JNIEXPORT jfloatArray JNICALL Java_philipyexushen_opencvhandler_HandlerWrapper_generalizedHoughBallard
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint, jdouble, jdouble, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
